#@formatter:off
name: Native Build

on: push


jobs:
    build:
        strategy:
            matrix:
                os: [ ubuntu-20.04, windows-latest ]
            fail-fast: false
        env:
            HYDRA_NATIVE_BUILD: true
        runs-on: ${{ matrix.os }}
        steps:
            -   uses: actions/checkout@v4
                with:
                    # Check out last 15 commits
                    fetch-depth: 15

            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'adopt'
                    cache: 'maven'

            -   name: NativeImage
                uses: graalvm/setup-graalvm@v1
                with:
                    java-version: '23'
                    distribution: 'graalvm-community'
                    cache: 'maven'
                    github-token: ${{ secrets.GITHUB_TOKEN }}

            -   name: "Install all with Maven"
                run: mvn --batch-mode clean install -DskipTests -T 1C
