#@formatter:off
name: Native Build

on: push

jobs:
    build:
        strategy:
            matrix:
                os: [ ubuntu-20.04]
            fail-fast: false
        runs-on: ${{ matrix.os }}
        steps:
            -   uses: actions/checkout@v4
                with:
                    # Check out last 15 commits
                    fetch-depth: 15

            -   name: Set up JDK 23
                uses: actions/setup-java@v4
                with:
                    java-version: '23'
                    distribution: 'adopt'
                    cache: 'maven'

            -   name: "Install with Maven"
                run: mvn --batch-mode clean install
